// Generated by CoffeeScript 1.4.0
(function() {
  var contentTypeHeader, should;

  should = require('../utils').should;

  contentTypeHeader = require('../../like/HTTP/ContentTypeHeader');

  describe('ContentTypeHeader', function() {
    it('should parse a simple Content-Type header correctly', function() {
      var h;
      h = new contentTypeHeader('application/json');
      h.tokens.should.eql([
        {
          mediaType: 'application/json',
          syntax: 'json'
        }
      ]);
      h = new contentTypeHeader('application/json,application/xml');
      return h.tokens.should.eql([
        {
          mediaType: 'application/json',
          syntax: 'json'
        }
      ]);
    });
    return it('should be able to stringify correctly', function() {
      var h;
      h = new contentTypeHeader('application/vnd.custom-v1+json;test=true;123=qwe;123=asd,application/vnd.custom-v1+xml;test=false;456=qwe');
      return h.toString().should.equal('application/vnd.custom-v1+json;123=qwe;test=true');
    });
  });

}).call(this);
