// Generated by CoffeeScript 1.4.0
(function() {
  var LinkHeader, should;

  should = require('../utils').should;

  LinkHeader = require('../../like/HTTP/LinkHeader');

  describe('LinkHeader', function() {
    it('should parse a simple Link header correctly', function() {
      var h;
      h = new LinkHeader('<https://klarna.com>');
      h.tokens.should.eql([
        {
          href: 'https://klarna.com'
        }
      ]);
      h = new LinkHeader('<https://klarna.com>,<https://google.com>');
      return h.tokens.should.eql([
        {
          href: 'https://klarna.com'
        }, {
          href: 'https://google.com'
        }
      ]);
    });
    it('should parse a complex Link header  correctly', function() {
      var h;
      h = new LinkHeader('<https://klarna.com>; rel=self');
      h.tokens.should.eql([
        {
          href: 'https://klarna.com',
          rel: 'self'
        }
      ]);
      h = new LinkHeader('<https://klarna.com>; rel=self; rel=edit, <https://google.com>; rel="self edit"; method');
      return h.tokens.should.eql([
        {
          href: 'https://klarna.com',
          rel: 'self'
        }, {
          href: 'https://google.com',
          rel: 'self edit',
          method: true
        }
      ]);
    });
    return it('should be able to stringify correctly', function() {
      var h;
      h = new LinkHeader('<https://klarna.com>; rel=self, <https://google.com>; rel="self edit"; method');
      return h.toString().should.equal('<https://klarna.com>;rel=self,<https://google.com>;rel="self edit";method');
    });
  });

}).call(this);
