// Generated by CoffeeScript 1.4.0
(function() {
  var chai;

  chai = require('chai');

  chai.Assertion.includeStack = true;

  exports.should = chai.should();

  exports._ = {};

  console.jog = function(arg) {
    return console.log(JSON.stringify(arg));
  };

}).call(this);
