// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(function() {
    "use strict";
    return function(str, pattern) {
      pattern = pattern || /[\u007f-\uffff]/g;
      str = str.replace(pattern, function(char) {
        return '\\u' + ('0000' + char.charCodeAt(0).toString(16)).slice(-4);
      });
      return str;
    };
  });

}).call(this);
