// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(function() {
    "use strict";
    return function(str, pattern) {
      pattern = pattern || /\\u([0-9a-fA-F]{4})/g;
      str = str.replace(pattern, function(match, digits) {
        return String.fromCharCode(parseInt(digits, 16));
      });
      return str;
    };
  });

}).call(this);
