// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['../underscore', '../_/type', '../_/map', '../_/prop', '../_/has', '../_/cloneDeep'], function(_, _type, _map, _prop, _has, _cloneDeep) {
    "use strict";
    return {
      compact: _.compact,
      type: _type,
      map: _map,
      prop: _prop,
      has: _has,
      cloneDeep: _cloneDeep
    };
  });

}).call(this);
