// Generated by CoffeeScript 1.4.0
(function() {
  var define,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['./_', './TokenizedHeader'], function(_, TokenizedHeader) {
    var AcceptHeader;
    return AcceptHeader = (function(_super) {

      __extends(AcceptHeader, _super);

      AcceptHeader.prototype._parseParamCallback = function(_arg) {
        var key, value;
        key = _arg[0], value = _arg[1];
        if (/^(application|audio|example|image|message|model|multipart|text|video)\/.+$/.test(key) && _.type(value) === 'undefined') {
          value = key;
          key = 'mediaType';
        }
        return [key, value];
      };

      AcceptHeader.prototype._parseTokenCallback = function(token) {
        var syntax;
        syntax = (/\/([a-zA-Z]+)$/.exec(token.mediaType) || [])[1];
        if (syntax == null) {
          syntax = (/\/.+\+([a-zA-Z]+)$/.exec(token.mediaType) || [])[1];
        }
        if (syntax) {
          token.syntax = syntax;
        }
        return token;
      };

      AcceptHeader.prototype._stringifyParamCallback = function(_arg) {
        var key, param, value;
        key = _arg[0], value = _arg[1];
        param = [];
        switch (key) {
          case 'mediaType':
          case 'syntax':
            [];
            break;
          default:
            param = [key, value];
        }
        return param;
      };

      AcceptHeader.prototype._stringifyTokenCallback = function(params, token) {
        params.unshift(token.mediaType);
        return params;
      };

      function AcceptHeader(header, config) {
        if (config == null) {
          config = {};
        }
        if (!(this instanceof AcceptHeader)) {
          return new AcceptHeader(header, config);
        }
        AcceptHeader.__super__.constructor.call(this, header, config);
      }

      return AcceptHeader;

    })(TokenizedHeader);
  });

}).call(this);
