// Generated by CoffeeScript 1.4.0
(function() {
  var define,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['./_', './AcceptHeader'], function(_, AcceptHeader) {
    var ContentTypeHeader;
    return ContentTypeHeader = (function(_super) {

      __extends(ContentTypeHeader, _super);

      ContentTypeHeader.prototype._token = {};

      _.prop.call(ContentTypeHeader, 'token');

      ContentTypeHeader.prototype._tokens = [ContentTypeHeader._token];

      function ContentTypeHeader(header, options) {
        if (options == null) {
          options = {};
        }
        if (!(this instanceof ContentTypeHeader)) {
          return new ContentTypeHeader(header, options);
        }
        ContentTypeHeader.__super__.constructor.call(this, header, options);
        this._tokens = this._tokens.slice(0, 1);
        this._token = this._tokens[0];
      }

      ContentTypeHeader.prototype._toString = function(instance) {
        this._tokens = this._tokens.slice(0, 1);
        return ContentTypeHeader.__super__._toString.call(this, instance);
      };

      return ContentTypeHeader;

    })(AcceptHeader);
  });

}).call(this);
