// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(function() {
    "use strict";

    var doNext;
    doNext = (typeof process !== "undefined" && process !== null ? process.nextTick : void 0) || setTimeout;
    (function(fun, context) {});
    return function(fun, context) {
      return function() {
        return doNext(function() {
          return fun.apply(context || this, arguments);
        });
      };
    };
  });

}).call(this);
