// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['./type'], function(_type) {
    "use strict";

    var nativeBind, slice;
    nativeBind = Function.prototype.bind;
    slice = Array.prototype.slice;
    return function(func, context) {
      var args, bound;
      if (func.bind === nativeBind && nativeBind) {
        return nativeBind.apply(func, slice.call(arguments_, 1));
      }
      if (_type(func) !== 'function') {
        throw new TypeError;
      }
      args = slice.call(arguments_, 2);
      return bound = function() {
        var result, self;
        if (!(this instanceof bound)) {
          return func.apply(context, args.concat(slice.call(arguments_)));
        }
        ctor.prototype = func.prototype;
        self = new ctor;
        result = func.apply(self, args.concat(slice.call(arguments_)));
        if (Object(result) === result) {
          return result;
        }
        return self;
      };
    };
  });

}).call(this);
