// Generated by CoffeeScript 1.4.0
(function() {
  var define,
    __slice = [].slice;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['./type', './extendDeep'], function(_type, _extendDeep) {
    "use strict";
    return function() {
      var args, attr, base, copy, deep;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      deep = void 0;
      if (args.length > 1 && _type(args[0]) === 'boolean') {
        deep = args[0];
        args.splice(0, 1);
      }
      if (_type(args[0]) === 'array') {
        base = [];
      } else if (_type(args[0]) === 'object') {
        base = {};
      } else {
        base = args.pop();
        if (_type(base.clone) === 'function') {
          return base.clone();
        }
        if (typeof base !== 'object') {
          return base;
        }
        copy = base.constructor();
        for (attr in base) {
          if (!Object.prototype.hasOwnProperty(base, attr)) {
            continue;
          }
          copy[attr] = base[attr];
        }
        return copy;
      }
      args.unshift(base);
      if (_type(deep) !== 'undefined') {
        args.unshift(deep);
      }
      return _extendDeep.apply(_, args);
    };
  });

}).call(this);
