// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['./has'], function(_has) {
    "use strict";

    var breaker, nativeForEach;
    nativeForEach = Array.prototype.forEach;
    breaker = {};
    return function(obj, iterator, context) {
      var i, key, l;
      if (obj == null) {
        return;
      }
      if (nativeForEach && obj.forEach === nativeForEach) {
        return obj.forEach(iterator, context);
      } else if (obj.length === +obj.length) {
        i = 0;
        l = obj.length;
        while (i < l) {
          if (iterator.call(context, obj[i], i, obj) === breaker) {
            return;
          }
          i++;
        }
      } else {
        for (key in obj) {
          if (_has(obj, key) && iterator.call(context, obj[key], key, obj) === breaker) {
            return;
          }
        }
      }
    };
  });

}).call(this);
