// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['node.extend'], function(extendDeep) {
    "use strict";
    return extendDeep;
  });

}).call(this);
