// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(function() {
    "use strict";

    var hasOwnProperty;
    hasOwnProperty = Object.prototype.hasOwnProperty;
    return function(obj, key) {
      return hasOwnProperty.call(obj, key);
    };
  });

}).call(this);
