// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['./async', './bind', './cloneDeep', './each', './extendDeep', './has', './map', './prop', './type'], function(_async, _bind, _cloneDeep, _each, _extendDeep, _has, _map, _prop, _type) {
    "use strict";
    return {
      async: _async,
      bind: _bind,
      cloneDeep: _cloneDeep,
      each: _each,
      extendDeep: _extendDeep,
      has: _has,
      map: _map,
      prop: _prop,
      type: _type
    };
  });

}).call(this);
