// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['./each'], function(_each) {
    "use strict";

    var nativeMap;
    nativeMap = Array.prototype.map;
    return function(obj, iterator, context) {
      var results;
      results = [];
      if (obj == null) {
        return results;
      }
      if (nativeMap && obj.map === nativeMap) {
        return obj.map(iterator, context);
      }
      _each(obj, function(value, index, list) {
        return results[results.length] = iterator.call(context, value, index, list);
      });
      return results;
    };
  });

}).call(this);
