// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(function() {
    "use strict";
    return function(name, desc) {
      var _ref, _ref1;
      if (desc == null) {
        desc = {};
      }
      desc.configurable = true;
      if ((_ref = desc.get) == null) {
        desc.get = function() {
          return this["_" + name];
        };
      }
      if ((_ref1 = desc.set) == null) {
        desc.set = function(value) {
          return this["_" + name] = value;
        };
      }
      return Object.defineProperty(this.prototype, name, desc);
    };
  });

}).call(this);
