// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(function() {
    "use strict";
    return function(obj) {
      if (obj == null) {
        return String(obj);
      }
      return Object.prototype.toString.call(obj).slice(8, -1).toLowerCase() || 'object';
    };
  });

}).call(this);
