// Generated by CoffeeScript 1.4.0
(function() {
  var define;

  if (typeof define !== 'function') {
    define = require('amdefine')(module);
  }

  define(['lodash', './_'], function(_, __) {
    "use strict";
    _.mixin(__);
    return _;
  });

}).call(this);
